return {
  Tree = "",
  -- Tree = "󰉦",
  Copilot = "",
  CopilotOff = "",
  Gear = "",
  BoldError = "",
  BoldWarning = "",
  LineAdded = "",
  LineModified = "",
  LineRemoved = "",
  FileDeleted = "",
  Tab = "󰌒",
  Neovim = "",
  Branch3 = "󰘬",
  NoBranch = "󱓌",
}
